creation_rules:
  - path_regex: secrets\.sops\.yaml$
    age: 3e45f2bc-b0e9-4315-b473-ac5e1b9d2e20,[agentctl, browser, dream-cycle, housekeeper, knowledge-base, memory, recall],[browser, teams],age14kmfvpspqf7l2jkzvzwdndya2agw5v74clpz0lqjuj0f7teyka4sjct3mg,age1fru272xhnqfzsy4k48ah4wtns9pyy5pwhj24kxj77yfpympfysuqvy7kmc,openrouter,pi,teams,teams-b,z-ai/glm-5.2
